### PR TITLE
Minor error. Prevents 'about' window to show itself.

### PR DESCRIPTION
**Pull request by rocus**
This is a very minor error. It can be ignored or implemented at your convenience!

### CODE REVIEW

**Comment by multani** [comment]
Do you think you can split this pull request into 2 pull requests? :)
Or actually, make only one, with the playlist fix, as I merged a better fix for the About window bug that you found in 4e34e0744cdc09f859256449832dac873f968490.

Can you give me a use-case for the playlist fix you are proposing, I don't really get what it does. Thanks!

**Comment by rocus** [comment]
On 06/05/2015 12:04 AM, Jonathan Ballet wrote:
>
> Do you think you can split this pull request into 2 pull requests? :)
> Or actually, make only one, with the playlist fix, as I merged a 
> better fix for the About window bug that you found in 4e34e07 
> <https://github.com/multani/sonata/commit/4e34e0744cdc09f859256449832dac873f968490>.
>
> Can you give me a use-case for the playlist fix you are proposing, I 
> don't really get what it does. Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/multani/sonata/pull/80#issuecomment-109069230>.
>
Hi Jonathan,

Thanks for your answer. Apparently I did something wrong with this 
github and git thing. My idea was to create two pull requests: one for 
the About window and one for the playlist feature.

I sent you a mail yesterday that I could not make the second pull 
request. The first went quite good and was for me just to practice 
because the error was all too obvious and the fix was a bit to quick and 
easy. I am looking for somebody who knows git/github who can explain 
things to me.

The thing that is really important to me is the playlist thing:

I listen to my music ofcourse (mp3's) but also a lot to radio stations. 
Most radio stations think that you listen to them on your PC. I have 
many audio streamers in the house (8) and some raspberry's with mpd and 
speakers attached. When you have the url's of the radio stations 
(sometimes not that easy) I place the url in a pls file with the 
appropriate name. These pls's are then served by ushare to my upnp 
streamer clients or loaded in my mpd's. These pls's I have in a 
directory structure in my music tree on a nas.

So far I used gmpc for my mpd's. The library menu( of gmps) of my mpd's 
shows a music tree and a radio tree. I can browse both. The structure of 
the radio tree has subtrees for me, for my wife, some common/local 
radiostations etc. Still a problem is how to get new radiostream url's.

Gmpc has some radio browsers but they are not very good.

Apart from that, gmpc is written in C (which I hate, maybe unfortunately 
for me).

Sonata seemed nice and easy and written in Python. So I got the idea to 
contribute to sonata. I fixed a few things (come back on that) but now 
run in some new problems / new things: git, github, glade, gtk.

My first contribution was just for testing (the about window)

The second is for me the most important: serving/loading pls files with 
radio streams. I am aware that you can add radiostreams in sonata but I 
think that saving pls's on the server (instead of on the client) is 
logical. It took some time to find out the difference between "load" and 
"add" in mpd. The additions for this fix are minimal and the effect is 
quite big in my opinion.

Another thing I did was repairing the coverart module. That was 
apparently already done for the newer sonata but it has some problems (I 
made an issue for that). I am planning to work on an other coverart 
plugin so everybody can choose the best one for him.

Rightnow I am working on a plugin for radio streams. It will be based on 
Radiode who have many radio stations in their database and serve the 
appropriate url. If that succeeds I will make one based on listenlive.eu

BTW. I think I have seen a few discussions about playlists in sonata and 
other mpd clients. There is also some confusion about how mpd clients 
handle playlists and if you can browse them and fill them yourself. I 
still don't know how to integrate it all (for example the favorites 
playlist and possibly generated playlists of radiode (still to program)

I hope you understand what I am aiming at with this playlist feature.


Hope to hear from you.

**Comment by multani** [comment]
Hi Rocus,

sorry for the late reply. I've read your message several times, and I'm still confused with what you want, but I may be too tired for this.

Would that be OK for you if we close this pull request, as the original bug was fixed 4e34e07 and that we move the conversation into other tickets?

You are talking here about several different things, and although I still don't understand what you want to do with the playlist and the radio streams (or is that 2 different things?), I'm getting even more confused with the other problems you are mentioning.

So, in order to make things clearer and help me to help you :), is it OK if we close this and I let you open new ones with a description of what you want?

Thanks!

**Comment by rocus** [comment]
OK, the thing about the "about" window you can close because it is 
clearly solved.

I will come back to the playlist issue and hopefully more clearly than 
so far.

In my mail I tried to give you an overview of what I am doing with Sonata:

- playlists ( for mp3's and radio streams) (this is one feature)
- cover art
- radio plugin

Apart from this I found some errors in the Sonata on github. I worked 
previously on Sonata as installed on my Ubuntu 12.04 system. The newer 
Sonata has some problems for which I filed issues on github.


I apologize for confusing you with my Emails: I try to separate the 
different issues and features
in the future. One of these days I hope to make a pull request for the 
playlist feature and I will try to describe it clearer.

**Pull request closed without merging**
